# Generated by Django 6.0.1 on 2026-01-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionresult',
            name='used_caching',
            field=models.BooleanField(default=False),
        ),
    ]
