# Generated by Django 6.0.1 on 2026-01-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copas', '0002_extractionresult_used_caching'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionresult',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
